# Web
server:
  port: 8081
  servlet:
    context-path: /
# Datasource
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/person_db
    username: hogehoge
    password: hogehoge
# MyBatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true

